packages:
  - "packages/syside-base"
  - "packages/syside-languageserver"
  - "packages/syside-cli"
  - "packages/syside-languageclient"
  - "packages/syside-protocol"
  - "packages/syside-vscode"
allowBuilds:
  '@swc/core': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
